general: &general
  cors:                     <%= ENV["CORS"] %>
  port:                     <%= ENV["PORT"] %>
  localhost:                <%= ENV["LOCALHOST"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>
  subdomain:                <%= ENV["SUBDOMAIN"] %>

redis: &redis
  redis_url:                <%= ENV["REDIS_URL"] %>
  redis_data:               <%= ENV["REDIS_DATA"] %>
  redis_cache:              <%= ENV["REDIS_CACHE"] %>
  redis_namespace:          <%= ENV["REDIS_NAMESPACE"] %>

mailer: &mailer
  mailer_to:                <%= ENV["MAILER_TO"] %>
  mailer_message:           <%= ENV["MAILER_MESSAGE"] %>

mailcatcher: &mailcatcher
  mailcatcher_protocol:     <%= ENV["MAILCATCHER_PROTOCOL"] %>
  mailcatcher_host:         <%= ENV["MAILCATCHER_HOST"] %>
  mailcatcher_port:         <%= ENV["MAILCATCHER_PORT"] %>

facebook: &facebook
  facebook_api_key:         <%= ENV["FACEBOOK_API_KEY"] %>
  facebook_api_secret:      <%= ENV["FACEBOOK_API_SECRET"] %>

linkedin: &linkedin
  linkedin_api_key:         <%= ENV["LINKEDIN_API_KEY"] %>
  linkedin_api_secret:      <%= ENV["LINKEDIN_API_SECRET"] %>

twitter: &twitter
  twitter_api_key:          <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret:       <%= ENV["TWITTER_API_SECRET"] %>

google: &google
  google_oauth2_api_key:    <%= ENV["GOOGLE_OAUTH2_API_KEY"] %>
  google_oauth2_api_secret: <%= ENV["GOOGLE_OAUTH2_API_SECRET"] %>

github: &github
  github_api_key:           <%= ENV["GITHUB_API_KEY"] %>
  github_api_secret:        <%= ENV["GITHUB_API_SECRET"] %>

geocoder: &geocoder
  geocoder_api_key:         <%= ENV["GEOCODER_API_KEY"] %>
  geoip_api_key:            <%= ENV["GEOIP_API_KEY"] %>

stripe: &stripe
  stripe_publishable_key:   <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key:        <%= ENV["STRIPE_SECRET_KEY"] %>

recaptcha: &recaptcha
  recaptcha_site_key:       <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key:     <%= ENV["RECAPTCHA_SECRET_KEY"] %>

firstdatae: &firstdatae
  firstdatae_login:         <%= ENV["FIRSTDATAE_LOGIN"] %>
  firstdatae_password:      <%= ENV["FIRSTDATAE_PASSWORD"] %>

development:
  <<: *general
  <<: *redis
  <<: *mailer
  <<: *mailcatcher
  <<: *facebook
  <<: *linkedin
  <<: *twitter
  <<: *google
  <<: *github
  <<: *geocoder
  <<: *stripe
  <<: *recaptcha
  <<: *firstdatae
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  web_console_ips:          <%= ENV["WEB_CONSOLE_IPS"] %>
  mailer_default:           <%= ENV["MAILER_DEFAULT"] %>

test:
  <<: *general
  <<: *redis
  <<: *mailer
  <<: *firstdatae
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  web_console_ips:          <%= ENV["WEB_CONSOLE_IPS"] %>

production:
  <<: *general
  <<: *redis
  <<: *mailer
  <<: *firstdatae
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
