general: &general
  cors:                   <%= ENV["CORS"] %>
  port:                   <%= ENV["PORT"] %>
  localhost:              <%= ENV["LOCALHOST"] %>
  domain_name:            <%= ENV["DOMAIN_NAME"] %>

redis: &redis
  redis_url:              <%= ENV["REDIS_URL"] %>
  redis_data:             <%= ENV["REDIS_DATA"] %>
  redis_cache:            <%= ENV["REDIS_CACHE"] %>
  redis_namespace:        <%= ENV["REDIS_NAMESPACE"] %>

development:
  <<: *general
  <<: *redis
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>

test:
  <<: *general
  <<: *redis
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>

production:
  <<: *general
  <<: *redis
  secret_key_base:        <%= ENV["SECRET_KEY_BASE"] %>
