general: &general
  cors:                     <%= ENV["CORS"] %>
  port:                     <%= ENV["PORT"] %>
  localhost:                <%= ENV["LOCALHOST"] %>
  domain_name:              <%= ENV["DOMAIN_NAME"] %>

redis: &redis
  redis_url:                <%= ENV["REDIS_URL"] %>
  redis_data:               <%= ENV["REDIS_DATA"] %>
  redis_cache:              <%= ENV["REDIS_CACHE"] %>
  redis_namespace:          <%= ENV["REDIS_NAMESPACE"] %>

facebook: &facebook
  facebook_api_key:         <%= ENV["FACEBOOK_API_KEY"] %>
  facebook_api_secret:      <%= ENV["FACEBOOK_API_SECRET"] %>

linkedin: &linkedin
  linkedin_api_key:         <%= ENV["LINKEDIN_API_KEY"] %>
  linkedin_api_secret:      <%= ENV["LINKEDIN_API_SECRET"] %>

twitter: &twitter
  twitter_api_key:          <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret:       <%= ENV["TWITTER_API_SECRET"] %>

google: &google
  google_oauth2_api_key:    <%= ENV["GOOGLE_OAUTH2_API_KEY"] %>
  google_oauth2_api_secret: <%= ENV["GOOGLE_OAUTH2_API_SECRET"] %>

development:
  <<: *general
  <<: *redis
  <<: *facebook
  <<: *linkedin
  <<: *twitter
  <<: *google
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  web_console_ips:          <%= ENV["WEB_CONSOLE_IPS"] %>
  mailer_default:           <%= ENV["MAILER_DEFAULT"] %>

test:
  <<: *general
  <<: *redis
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
  web_console_ips:          <%= ENV["WEB_CONSOLE_IPS"] %>

production:
  <<: *general
  <<: *redis
  secret_key_base:          <%= ENV["SECRET_KEY_BASE"] %>
